[WEB-5183] Creating the InteractivePurchase message
serato/web-sup-php-sdk pull request #55
Opened 2021-04-13 03:46 UTC by ben-farrelly

This message captures:
* User ID
* Products
* Order Date
* Order ID

This data in the message will be used in the SUP app to update the user profile.

2021-04-14 02:45 UTC, mjliang reviewed
Looks good, I just have one question. Do we need more test cases to cover more scenarios? For example `Make an order with the wrong format of the data`

2021-04-14 22:12 UTC, ben-farrelly commented
> Looks good, I just have one question. Do we need more test cases to cover more scenarios? For example `Make an order with the wrong format of the data`

Hmm I was thinking about this, but this is type safe so the only thing to test is the product array, but I think that's better suited to the SUP app rather than the SDK, the SDK just wants some product data and the app has the schema for the product information.
Typically it seems like we don't do that schema validation at the SDK level. 
Although it's an interesting thought, what do you think?

2021-04-14 22:47 UTC, takayuki-serato requested changes
It was fine until I noticed you used copy and paste

2021-04-14 22:47 UTC, takayuki-serato commented on src/Message/InteractivePurchase.php
> +     * Set the Product ID of the interactive purchase
Documentation is wrong G and can you chuck the schema for the array on here too pls

2021-04-14 22:47 UTC, takayuki-serato commented on src/Message/InteractivePurchase.php
> +     * Get the Product ID from an interactive purchase
No

2021-04-14 22:49 UTC, ben-farrelly commented on src/Message/InteractivePurchase.php
> +     * Get the Product ID from an interactive purchase
delet

2021-04-14 23:31 UTC, takayuki-serato approved these changes

2021-04-14 23:51 UTC, ben-farrelly commented
Are you okay with this PR to be merged @mjliang ?

2021-04-15 01:38 UTC, matiaslg13 approved these changes
I checked the PR and also MJ's suggestions. I think, like Ben said, those checks should be at a SUP level, not SDK.

2021-04-15 01:47 UTC, ben-farrelly commented
Okay, I'm going to merge this now and get this published to packagist.

2021-04-15 01:47 UTC, merged